# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: widgetario
      component: stock-api
  template:
    metadata:
      labels:
        app: widgetario
        component: stock-api
    spec:
      containers:
        - name: app
          image: widgetario/stock-api:21.03
          ports:
            - containerPort: 80
              name: http

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: stock-api
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: widgetario
    component: stock-api
  type: ClusterIP
