# Ingress 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: widgetario-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  rules:
    - host: widgetario.local
      http:
        paths:
          - path: /products(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: products-api
                port:
                  number: 80
          - path: /stock(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: stock-api
                port:
                  number: 80
          - path: /web(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: widgetario-web
                port:
                  number: 80
